package TeoriaClase1.CajaConHerencia;

public interface Caja {

	public void insertar(Elemento elem);
	public void eliminar(Elemento elem);
	public boolean buscar(Elemento elem);
	public Elemento recuperarAlguno();
}

/*OBSERVEN QUE ESTA INTERFACE NO DEFINE LA ESPECIFICACIÓN DE LAS OPERACIONES
 * INSERTAR: ¿QUE PASA SI ELEM YA ESTA EN LA CAJA?, ¿PUEDE LA CAJA LLENARSE?
 * ELIMINAR: ¿QUE PASA SI ELEM ESTA REPEDIDO?*
 * RECUPERAR ALGUNO: ¿QUÉ RETORNA SI LA CAJA ESTA VACIA?/
 * EN LAS INTERFACES QUE VAMOS A UTILIZAR PARA CREAR NUESTRAS ESTRUCTURAS DE DATOS VAN A 
 * ENCONTRAR ESPECIFICACIONES MUY DETALLADAS DE CADA UNA DE LAS OPERACIONES.
 */